name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Este trigger se activará con cualquier tag que comience con 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          TAG=${GITHUB_REF##*/}  # Obtiene el nombre del tag
          docker build -t alvarocero3/retos1:$TAG .

      - name: Push Docker Image
        run: |
          TAG=${GITHUB_REF##*/}  # Obtiene el nombre del tag
          docker push alvarocero3/retos1:$TAG
